#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/gts7fewifi

PRODUCT_COPY_FILES += \
    vendor/samsung/gts7fewifi/proprietary/recovery/root/vendor/firmware/tsp_focaltech/ft8203_gts7xllite.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/tsp_focaltech/ft8203_gts7xllite.bin \
    vendor/samsung/gts7fewifi/proprietary/recovery/root/vendor/firmware/tsp_himax/hx83121a_gts7xllite.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/tsp_himax/hx83121a_gts7xllite.bin \
    vendor/samsung/gts7fewifi/proprietary/vendor/etc/audconf/OPEN/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OPEN/Bluetooth_cal.acdb \
    vendor/samsung/gts7fewifi/proprietary/vendor/etc/audconf/OPEN/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OPEN/General_cal.acdb \
    vendor/samsung/gts7fewifi/proprietary/vendor/etc/audconf/OPEN/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OPEN/Global_cal.acdb \
    vendor/samsung/gts7fewifi/proprietary/vendor/etc/audconf/OPEN/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OPEN/Handset_cal.acdb \
    vendor/samsung/gts7fewifi/proprietary/vendor/etc/audconf/OPEN/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OPEN/Hdmi_cal.acdb \
    vendor/samsung/gts7fewifi/proprietary/vendor/etc/audconf/OPEN/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OPEN/Headset_cal.acdb \
    vendor/samsung/gts7fewifi/proprietary/vendor/etc/audconf/OPEN/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OPEN/Speaker_cal.acdb \
    vendor/samsung/gts7fewifi/proprietary/vendor/etc/audconf/OPEN/workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OPEN/workspaceFile.qwsp \
    vendor/samsung/gts7fewifi/proprietary/vendor/etc/qdcm_calib_data_ss_dsi_panel_FT8203_TS124QDM_WQXGA.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_ss_dsi_panel_FT8203_TS124QDM_WQXGA.xml \
    vendor/samsung/gts7fewifi/proprietary/vendor/etc/qdcm_calib_data_ss_dsi_panel_HX83102_TV104WUM_WUXGA.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_ss_dsi_panel_HX83102_TV104WUM_WUXGA.xml \
    vendor/samsung/gts7fewifi/proprietary/vendor/etc/qdcm_calib_data_ss_dsi_panel_HX83121_PPC357DB11_WQXGA.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_ss_dsi_panel_HX83121_PPC357DB11_WQXGA.xml \
    vendor/samsung/gts7fewifi/proprietary/vendor/etc/sensors/config/bridge_driver_2.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/bridge_driver_2.json \
    vendor/samsung/gts7fewifi/proprietary/vendor/etc/sensors/config/kodiak_ak991x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kodiak_ak991x_0.json \
    vendor/samsung/gts7fewifi/proprietary/vendor/etc/sensors/config/kodiak_lsm6dso_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kodiak_lsm6dso_0.json \
    vendor/samsung/gts7fewifi/proprietary/vendor/etc/sensors/config/kodiak_veml3235_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kodiak_veml3235_0.json \
    vendor/samsung/gts7fewifi/proprietary/vendor/etc/sensors/config/kodiak_veml3235_1.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kodiak_veml3235_1.json \
    vendor/samsung/gts7fewifi/proprietary/vendor/etc/sensors/config/lsm6dso_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lsm6dso_0.json \
    vendor/samsung/gts7fewifi/proprietary/vendor/etc/sensors/config/veml3235_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/veml3235_0.json \
    vendor/samsung/gts7fewifi/proprietary/vendor/etc/sensors/config/veml3235_1.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/veml3235_1.json \
    vendor/samsung/gts7fewifi/proprietary/vendor/etc/sensors/hals.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/hals.conf \
    vendor/samsung/gts7fewifi/proprietary/vendor/firmware/bt_nvm_loading.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/bt_nvm_loading.xml \
    vendor/samsung/gts7fewifi/proprietary/vendor/firmware/cs35l45-dsp1-spk-prot-calib.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l45-dsp1-spk-prot-calib.bin \
    vendor/samsung/gts7fewifi/proprietary/vendor/firmware/cs35l45-dsp1-spk-prot.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l45-dsp1-spk-prot.bin \
    vendor/samsung/gts7fewifi/proprietary/vendor/firmware/cs35l45-dsp1-spk-prot.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l45-dsp1-spk-prot.wmfw \
    vendor/samsung/gts7fewifi/proprietary/vendor/firmware/dax_param.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dax_param.bin \
    vendor/samsung/gts7fewifi/proprietary/vendor/firmware/dbmd8_va_asrp_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dbmd8_va_asrp_fw.bin \
    vendor/samsung/gts7fewifi/proprietary/vendor/firmware/dbmd8_va_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dbmd8_va_fw.bin \
    vendor/samsung/gts7fewifi/proprietary/vendor/firmware/epen/w9021_gts7xllite.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/epen/w9021_gts7xllite.bin \
    vendor/samsung/gts7fewifi/proprietary/vendor/firmware/keyboard_stm/stm32_gts7llite.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/keyboard_stm/stm32_gts7llite.bin \
    vendor/samsung/gts7fewifi/proprietary/vendor/firmware/tsp_focaltech/ft8203_gts7xllite.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/tsp_focaltech/ft8203_gts7xllite.bin \
    vendor/samsung/gts7fewifi/proprietary/vendor/firmware/tsp_himax/hx83121a_gts7xllite.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/tsp_himax/hx83121a_gts7xllite.bin \
    vendor/samsung/gts7fewifi/proprietary/vendor/firmware/wlan/rev2/wpss.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/rev2/wpss.b01 \
    vendor/samsung/gts7fewifi/proprietary/vendor/firmware/wlan/rev2/wpss.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/rev2/wpss.mdt \
    vendor/samsung/gts7fewifi/proprietary/vendor/firmware/wlan/rev3/wpss.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/rev3/wpss.b00 \
    vendor/samsung/gts7fewifi/proprietary/vendor/firmware/wlan/rev3/wpss.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/rev3/wpss.b01 \
    vendor/samsung/gts7fewifi/proprietary/vendor/firmware/wlan/rev3/wpss.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/rev3/wpss.b02 \
    vendor/samsung/gts7fewifi/proprietary/vendor/firmware/wlan/rev3/wpss.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/rev3/wpss.b03 \
    vendor/samsung/gts7fewifi/proprietary/vendor/firmware/wlan/rev3/wpss.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/rev3/wpss.b04 \
    vendor/samsung/gts7fewifi/proprietary/vendor/firmware/wlan/rev3/wpss.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/rev3/wpss.b05 \
    vendor/samsung/gts7fewifi/proprietary/vendor/firmware/wlan/rev3/wpss.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/rev3/wpss.b06 \
    vendor/samsung/gts7fewifi/proprietary/vendor/firmware/wlan/rev3/wpss.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/rev3/wpss.b07 \
    vendor/samsung/gts7fewifi/proprietary/vendor/firmware/wlan/rev3/wpss.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/rev3/wpss.mdt \
    vendor/samsung/gts7fewifi/proprietary/vendor/firmware/wlan/rev4/wpss.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/rev4/wpss.b00 \
    vendor/samsung/gts7fewifi/proprietary/vendor/firmware/wlan/rev4/wpss.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/rev4/wpss.b01 \
    vendor/samsung/gts7fewifi/proprietary/vendor/firmware/wlan/rev4/wpss.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/rev4/wpss.b02 \
    vendor/samsung/gts7fewifi/proprietary/vendor/firmware/wlan/rev4/wpss.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/rev4/wpss.b03 \
    vendor/samsung/gts7fewifi/proprietary/vendor/firmware/wlan/rev4/wpss.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/rev4/wpss.b04 \
    vendor/samsung/gts7fewifi/proprietary/vendor/firmware/wlan/rev4/wpss.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/rev4/wpss.b05 \
    vendor/samsung/gts7fewifi/proprietary/vendor/firmware/wlan/rev4/wpss.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/rev4/wpss.b06 \
    vendor/samsung/gts7fewifi/proprietary/vendor/firmware/wlan/rev4/wpss.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/rev4/wpss.b07 \
    vendor/samsung/gts7fewifi/proprietary/vendor/firmware/wlan/rev4/wpss.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/rev4/wpss.mdt \
    vendor/samsung/gts7fewifi/proprietary/vendor/firmware/wlan/rev5/wpss.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/rev5/wpss.b00 \
    vendor/samsung/gts7fewifi/proprietary/vendor/firmware/wlan/rev5/wpss.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/rev5/wpss.b01 \
    vendor/samsung/gts7fewifi/proprietary/vendor/firmware/wlan/rev5/wpss.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/rev5/wpss.b02 \
    vendor/samsung/gts7fewifi/proprietary/vendor/firmware/wlan/rev5/wpss.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/rev5/wpss.b03 \
    vendor/samsung/gts7fewifi/proprietary/vendor/firmware/wlan/rev5/wpss.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/rev5/wpss.b04 \
    vendor/samsung/gts7fewifi/proprietary/vendor/firmware/wlan/rev5/wpss.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/rev5/wpss.b05 \
    vendor/samsung/gts7fewifi/proprietary/vendor/firmware/wlan/rev5/wpss.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/rev5/wpss.b06 \
    vendor/samsung/gts7fewifi/proprietary/vendor/firmware/wlan/rev5/wpss.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/rev5/wpss.b07 \
    vendor/samsung/gts7fewifi/proprietary/vendor/firmware/wlan/rev5/wpss.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/rev5/wpss.mdt \
    vendor/samsung/gts7fewifi/proprietary/vendor/firmware/wlan/rev6/wpss.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/rev6/wpss.b00 \
    vendor/samsung/gts7fewifi/proprietary/vendor/firmware/wlan/rev6/wpss.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/rev6/wpss.b01 \
    vendor/samsung/gts7fewifi/proprietary/vendor/firmware/wlan/rev6/wpss.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/rev6/wpss.b02 \
    vendor/samsung/gts7fewifi/proprietary/vendor/firmware/wlan/rev6/wpss.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/rev6/wpss.b03 \
    vendor/samsung/gts7fewifi/proprietary/vendor/firmware/wlan/rev6/wpss.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/rev6/wpss.b04 \
    vendor/samsung/gts7fewifi/proprietary/vendor/firmware/wlan/rev6/wpss.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/rev6/wpss.b05 \
    vendor/samsung/gts7fewifi/proprietary/vendor/firmware/wlan/rev6/wpss.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/rev6/wpss.b06 \
    vendor/samsung/gts7fewifi/proprietary/vendor/firmware/wlan/rev6/wpss.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/rev6/wpss.b07 \
    vendor/samsung/gts7fewifi/proprietary/vendor/firmware/wlan/rev6/wpss.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/rev6/wpss.mdt \
    vendor/samsung/gts7fewifi/proprietary/vendor/firmware/wlan/rev7/wpss.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/rev7/wpss.b01 \
    vendor/samsung/gts7fewifi/proprietary/vendor/firmware/wlan/rev7/wpss.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/rev7/wpss.mdt \
    vendor/samsung/gts7fewifi/proprietary/vendor/firmware/wlan/rev8/wpss.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/rev8/wpss.b00 \
    vendor/samsung/gts7fewifi/proprietary/vendor/firmware/wlan/rev8/wpss.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/rev8/wpss.b01 \
    vendor/samsung/gts7fewifi/proprietary/vendor/firmware/wlan/rev8/wpss.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/rev8/wpss.b02 \
    vendor/samsung/gts7fewifi/proprietary/vendor/firmware/wlan/rev8/wpss.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/rev8/wpss.b03 \
    vendor/samsung/gts7fewifi/proprietary/vendor/firmware/wlan/rev8/wpss.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/rev8/wpss.b04 \
    vendor/samsung/gts7fewifi/proprietary/vendor/firmware/wlan/rev8/wpss.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/rev8/wpss.b05 \
    vendor/samsung/gts7fewifi/proprietary/vendor/firmware/wlan/rev8/wpss.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/rev8/wpss.b07 \
    vendor/samsung/gts7fewifi/proprietary/vendor/firmware/wlan/rev8/wpss.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/rev8/wpss.mdt \
    vendor/samsung/gts7fewifi/proprietary/vendor/firmware/wlan/rev9/wpss.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/rev9/wpss.b00 \
    vendor/samsung/gts7fewifi/proprietary/vendor/firmware/wlan/rev9/wpss.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/rev9/wpss.b01 \
    vendor/samsung/gts7fewifi/proprietary/vendor/firmware/wlan/rev9/wpss.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/rev9/wpss.b02 \
    vendor/samsung/gts7fewifi/proprietary/vendor/firmware/wlan/rev9/wpss.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/rev9/wpss.b03 \
    vendor/samsung/gts7fewifi/proprietary/vendor/firmware/wlan/rev9/wpss.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/rev9/wpss.b04 \
    vendor/samsung/gts7fewifi/proprietary/vendor/firmware/wlan/rev9/wpss.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/rev9/wpss.b05 \
    vendor/samsung/gts7fewifi/proprietary/vendor/firmware/wlan/rev9/wpss.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/rev9/wpss.b07 \
    vendor/samsung/gts7fewifi/proprietary/vendor/firmware/wlan/rev9/wpss.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/rev9/wpss.mdt \
    vendor/samsung/gts7fewifi/proprietary/vendor/firmware/wpss.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/wpss.b00 \
    vendor/samsung/gts7fewifi/proprietary/vendor/firmware/wpss.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/wpss.b01 \
    vendor/samsung/gts7fewifi/proprietary/vendor/firmware/wpss.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/wpss.b02 \
    vendor/samsung/gts7fewifi/proprietary/vendor/firmware/wpss.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/wpss.b03 \
    vendor/samsung/gts7fewifi/proprietary/vendor/firmware/wpss.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/wpss.b04 \
    vendor/samsung/gts7fewifi/proprietary/vendor/firmware/wpss.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/wpss.b05 \
    vendor/samsung/gts7fewifi/proprietary/vendor/firmware/wpss.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/wpss.b06 \
    vendor/samsung/gts7fewifi/proprietary/vendor/firmware/wpss.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/wpss.b07 \
    vendor/samsung/gts7fewifi/proprietary/vendor/firmware/wpss.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/wpss.mdt \
    vendor/samsung/gts7fewifi/proprietary/vendor/lib64/camera/com.qti.tuned.default.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.default.bin \
    vendor/samsung/gts7fewifi/proprietary/vendor/lib64/camera/com.samsung.sensormodule.0_0_sony_imx355.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.sensormodule.0_0_sony_imx355.bin \
    vendor/samsung/gts7fewifi/proprietary/vendor/lib64/camera/com.samsung.sensormodule.13_lsi_gc5035.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.sensormodule.13_lsi_gc5035.bin \
    vendor/samsung/gts7fewifi/proprietary/vendor/lib64/camera/com.samsung.sensormodule.1_lsi_gc5035.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.sensormodule.1_lsi_gc5035.bin \
    vendor/samsung/gts7fewifi/proprietary/vendor/lib64/camera/com.samsung.tuned.lsi_gc5035.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.tuned.lsi_gc5035.bin \
    vendor/samsung/gts7fewifi/proprietary/vendor/lib64/camera/com.samsung.tuned.sony_imx355.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.tuned.sony_imx355.bin \
    vendor/samsung/gts7fewifi/proprietary/vendor/lib64/camera/f_dual_calibration.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/f_dual_calibration.bin \
    vendor/samsung/gts7fewifi/proprietary/vendor/lib64/camera/t_t10_dual_calibration.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/t_t10_dual_calibration.bin \
    vendor/samsung/gts7fewifi/proprietary/vendor/lib64/camera/uw_dual_calibration.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/uw_dual_calibration.bin \
    vendor/samsung/gts7fewifi/proprietary/vendor/lib64/camera/w_dual_calibration.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/w_dual_calibration.bin

PRODUCT_PACKAGES += \
    sensors.grip \
    sensors.ssc \
    audio.primary.lahaina \
    libspeakercalibration \
    com.qti.eeprom.irs2381c_polar \
    com.qti.eeprom.sec2qcconversion \
    com.qti.eeprom.truly_cmb433 \
    com.samsung.sensor.gc5035 \
    com.samsung.sensor.imx355 \
    com.qti.camx.chiiqutils \
    com.qti.eisv2 \
    com.qti.eisv3 \
    com.qti.hvx.addconstant \
    com.qti.hvx.binning \
    com.qti.node.depth \
    com.qti.node.dewarp \
    com.qti.node.dummyrtb \
    com.qti.node.dummysat \
    com.qti.node.eisv2 \
    com.qti.node.factorydump \
    com.qti.node.fcv \
    com.qti.node.gpu \
    com.qti.node.memcpy \
    com.qti.node.ml \
    com.qti.node.sbi \
    com.qti.node.stich \
    com.qti.node.swaidenoiser \
    com.qti.node.swcac \
    com.qti.node.swlsc \
    com.qti.node.swmctf \
    com.qti.node.swmfnr \
    com.qti.node.swpreprocess \
    com.qti.node.swregistration \
    com.qti.stats.aec \
    com.qti.stats.aecwrapper \
    com.qti.stats.aecxcore \
    com.qti.stats.af \
    com.qti.stats.afd \
    com.qti.stats.afwrapper \
    com.qti.stats.asd \
    com.qti.stats.awb \
    com.qti.stats.awbwrapper \
    com.qti.stats.cnndriver \
    com.qti.stats.haf \
    com.qti.stats.hafoverride \
    com.qti.stats.pdlib \
    com.qti.stats.pdlibsony \
    com.qti.stats.pdlibwrapper \
    com.qti.stats.tracker \
    com.qtistatic.stats.aec \
    com.qtistatic.stats.af \
    com.qtistatic.stats.awb \
    com.qtistatic.stats.pdlib \
    com.samsung.node.capture_bokeh \
    com.samsung.node.capture_fusion \
    com.samsung.node.realtimebokeh \
    com.samsung.node.resolution \
    com.samsung.node.smooth_transition \
    com.samsung.node.uniplugin_capture \
    com.samsung.node.uniplugin_preview \
    com.samsung.node.uniplugin_recording \
    com.samsung.node.uniplugin_vdis \
    com.ss.stats.aec \
    com.ss.stats.af \
    com.ss.stats.awb \
    com.ss.stats.pdlib \
    libdepthmapwrapper_secure \
    com.qti.feature2.anchorsync \
    com.qti.feature2.demux \
    com.qti.feature2.derivedoffline \
    com.qti.feature2.frameselect \
    com.qti.feature2.fusion \
    com.qti.feature2.generic \
    com.qti.feature2.gs.kodiak \
    com.qti.feature2.gs.sm8350 \
    com.qti.feature2.hdr \
    com.qti.feature2.mcreprocrt \
    com.qti.feature2.memcpy \
    com.qti.feature2.mfsr \
    com.qti.feature2.ml \
    com.qti.feature2.mux \
    com.qti.feature2.qcfa \
    com.qti.feature2.rawhdr \
    com.qti.feature2.realtimeserializer \
    com.qti.feature2.rt \
    com.qti.feature2.rtmcx \
    com.qti.feature2.serializer \
    com.qti.feature2.statsregeneration \
    com.qti.feature2.stub \
    com.qti.feature2.swmf \
    camera.qcom \
    com.qti.chi.override \
    libsec2qc_conversion \
    HotwordEnrollmentOKGoogleEx3TL3210 \
    HotwordEnrollmentXGoogleEx3TL3210
